---
- name: Process each list on {{ pihole_instance.name }}
  sbarbett.pihole.bulk_list_update:
    url: "{{ pihole_instance.name }}"
    password: "{{ pihole_instance.password }}"
    lists: "{{ pihole_lists }}"
